// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messaging/data.proto

package messaging

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AppendRequest struct {
	Cid                  int32    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Csn                  int32    `protobuf:"varint,2,opt,name=csn,proto3" json:"csn,omitempty"`
	Record               string   `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendRequest) Reset()         { *m = AppendRequest{} }
func (m *AppendRequest) String() string { return proto.CompactTextString(m) }
func (*AppendRequest) ProtoMessage()    {}
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_9aa9a57ed7557f0c, []int{0}
}
func (m *AppendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendRequest.Unmarshal(m, b)
}
func (m *AppendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendRequest.Marshal(b, m, deterministic)
}
func (dst *AppendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendRequest.Merge(dst, src)
}
func (m *AppendRequest) XXX_Size() int {
	return xxx_messageInfo_AppendRequest.Size(m)
}
func (m *AppendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppendRequest proto.InternalMessageInfo

func (m *AppendRequest) GetCid() int32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *AppendRequest) GetCsn() int32 {
	if m != nil {
		return m.Csn
	}
	return 0
}

func (m *AppendRequest) GetRecord() string {
	if m != nil {
		return m.Record
	}
	return ""
}

type AppendResponse struct {
	Csn                  int32    `protobuf:"varint,1,opt,name=csn,proto3" json:"csn,omitempty"`
	Gsn                  int32    `protobuf:"varint,2,opt,name=gsn,proto3" json:"gsn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppendResponse) Reset()         { *m = AppendResponse{} }
func (m *AppendResponse) String() string { return proto.CompactTextString(m) }
func (*AppendResponse) ProtoMessage()    {}
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_9aa9a57ed7557f0c, []int{1}
}
func (m *AppendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppendResponse.Unmarshal(m, b)
}
func (m *AppendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppendResponse.Marshal(b, m, deterministic)
}
func (dst *AppendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppendResponse.Merge(dst, src)
}
func (m *AppendResponse) XXX_Size() int {
	return xxx_messageInfo_AppendResponse.Size(m)
}
func (m *AppendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppendResponse proto.InternalMessageInfo

func (m *AppendResponse) GetCsn() int32 {
	if m != nil {
		return m.Csn
	}
	return 0
}

func (m *AppendResponse) GetGsn() int32 {
	if m != nil {
		return m.Gsn
	}
	return 0
}

type ReplicateRequest struct {
	ServerID             int32    `protobuf:"varint,1,opt,name=serverID,proto3" json:"serverID,omitempty"`
	Record               string   `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicateRequest) Reset()         { *m = ReplicateRequest{} }
func (m *ReplicateRequest) String() string { return proto.CompactTextString(m) }
func (*ReplicateRequest) ProtoMessage()    {}
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_9aa9a57ed7557f0c, []int{2}
}
func (m *ReplicateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicateRequest.Unmarshal(m, b)
}
func (m *ReplicateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicateRequest.Marshal(b, m, deterministic)
}
func (dst *ReplicateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicateRequest.Merge(dst, src)
}
func (m *ReplicateRequest) XXX_Size() int {
	return xxx_messageInfo_ReplicateRequest.Size(m)
}
func (m *ReplicateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicateRequest proto.InternalMessageInfo

func (m *ReplicateRequest) GetServerID() int32 {
	if m != nil {
		return m.ServerID
	}
	return 0
}

func (m *ReplicateRequest) GetRecord() string {
	if m != nil {
		return m.Record
	}
	return ""
}

// No response needed. In event of failure, we should finalize everything
type ReplicateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicateResponse) Reset()         { *m = ReplicateResponse{} }
func (m *ReplicateResponse) String() string { return proto.CompactTextString(m) }
func (*ReplicateResponse) ProtoMessage()    {}
func (*ReplicateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_9aa9a57ed7557f0c, []int{3}
}
func (m *ReplicateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicateResponse.Unmarshal(m, b)
}
func (m *ReplicateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicateResponse.Marshal(b, m, deterministic)
}
func (dst *ReplicateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicateResponse.Merge(dst, src)
}
func (m *ReplicateResponse) XXX_Size() int {
	return xxx_messageInfo_ReplicateResponse.Size(m)
}
func (m *ReplicateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicateResponse proto.InternalMessageInfo

type CommitRequest struct {
	// Gsn to start counting off of for the 0th server
	StartGlobalSequenceNum int32 `protobuf:"varint,1,opt,name=startGlobalSequenceNum,proto3" json:"startGlobalSequenceNum,omitempty"`
	// Offsets of the newly ordered records
	Offsets []int32 `protobuf:"varint,2,rep,packed,name=offsets,proto3" json:"offsets,omitempty"`
	// Should be in order of the server ID
	CommittedCuts        []int32  `protobuf:"varint,3,rep,packed,name=committedCuts,proto3" json:"committedCuts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitRequest) Reset()         { *m = CommitRequest{} }
func (m *CommitRequest) String() string { return proto.CompactTextString(m) }
func (*CommitRequest) ProtoMessage()    {}
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_9aa9a57ed7557f0c, []int{4}
}
func (m *CommitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitRequest.Unmarshal(m, b)
}
func (m *CommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitRequest.Marshal(b, m, deterministic)
}
func (dst *CommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitRequest.Merge(dst, src)
}
func (m *CommitRequest) XXX_Size() int {
	return xxx_messageInfo_CommitRequest.Size(m)
}
func (m *CommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitRequest proto.InternalMessageInfo

func (m *CommitRequest) GetStartGlobalSequenceNum() int32 {
	if m != nil {
		return m.StartGlobalSequenceNum
	}
	return 0
}

func (m *CommitRequest) GetOffsets() []int32 {
	if m != nil {
		return m.Offsets
	}
	return nil
}

func (m *CommitRequest) GetCommittedCuts() []int32 {
	if m != nil {
		return m.CommittedCuts
	}
	return nil
}

type CommitResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitResponse) Reset()         { *m = CommitResponse{} }
func (m *CommitResponse) String() string { return proto.CompactTextString(m) }
func (*CommitResponse) ProtoMessage()    {}
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_9aa9a57ed7557f0c, []int{5}
}
func (m *CommitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitResponse.Unmarshal(m, b)
}
func (m *CommitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitResponse.Marshal(b, m, deterministic)
}
func (dst *CommitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitResponse.Merge(dst, src)
}
func (m *CommitResponse) XXX_Size() int {
	return xxx_messageInfo_CommitResponse.Size(m)
}
func (m *CommitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommitResponse proto.InternalMessageInfo

type SubscribeRequest struct {
	SubscriptionGsn      int32    `protobuf:"varint,1,opt,name=subscription_gsn,json=subscriptionGsn,proto3" json:"subscription_gsn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_9aa9a57ed7557f0c, []int{6}
}
func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (dst *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(dst, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetSubscriptionGsn() int32 {
	if m != nil {
		return m.SubscriptionGsn
	}
	return 0
}

type SubscribeResponse struct {
	Gsn                  int32    `protobuf:"varint,1,opt,name=gsn,proto3" json:"gsn,omitempty"`
	Record               string   `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeResponse) Reset()         { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()    {}
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_9aa9a57ed7557f0c, []int{7}
}
func (m *SubscribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeResponse.Unmarshal(m, b)
}
func (m *SubscribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeResponse.Marshal(b, m, deterministic)
}
func (dst *SubscribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeResponse.Merge(dst, src)
}
func (m *SubscribeResponse) XXX_Size() int {
	return xxx_messageInfo_SubscribeResponse.Size(m)
}
func (m *SubscribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeResponse proto.InternalMessageInfo

func (m *SubscribeResponse) GetGsn() int32 {
	if m != nil {
		return m.Gsn
	}
	return 0
}

func (m *SubscribeResponse) GetRecord() string {
	if m != nil {
		return m.Record
	}
	return ""
}

type TrimRequest struct {
	Gsn                  int32    `protobuf:"varint,1,opt,name=gsn,proto3" json:"gsn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrimRequest) Reset()         { *m = TrimRequest{} }
func (m *TrimRequest) String() string { return proto.CompactTextString(m) }
func (*TrimRequest) ProtoMessage()    {}
func (*TrimRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_9aa9a57ed7557f0c, []int{8}
}
func (m *TrimRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrimRequest.Unmarshal(m, b)
}
func (m *TrimRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrimRequest.Marshal(b, m, deterministic)
}
func (dst *TrimRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrimRequest.Merge(dst, src)
}
func (m *TrimRequest) XXX_Size() int {
	return xxx_messageInfo_TrimRequest.Size(m)
}
func (m *TrimRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TrimRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TrimRequest proto.InternalMessageInfo

func (m *TrimRequest) GetGsn() int32 {
	if m != nil {
		return m.Gsn
	}
	return 0
}

type TrimResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrimResponse) Reset()         { *m = TrimResponse{} }
func (m *TrimResponse) String() string { return proto.CompactTextString(m) }
func (*TrimResponse) ProtoMessage()    {}
func (*TrimResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_9aa9a57ed7557f0c, []int{9}
}
func (m *TrimResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrimResponse.Unmarshal(m, b)
}
func (m *TrimResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrimResponse.Marshal(b, m, deterministic)
}
func (dst *TrimResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrimResponse.Merge(dst, src)
}
func (m *TrimResponse) XXX_Size() int {
	return xxx_messageInfo_TrimResponse.Size(m)
}
func (m *TrimResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TrimResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TrimResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AppendRequest)(nil), "messaging.AppendRequest")
	proto.RegisterType((*AppendResponse)(nil), "messaging.AppendResponse")
	proto.RegisterType((*ReplicateRequest)(nil), "messaging.ReplicateRequest")
	proto.RegisterType((*ReplicateResponse)(nil), "messaging.ReplicateResponse")
	proto.RegisterType((*CommitRequest)(nil), "messaging.CommitRequest")
	proto.RegisterType((*CommitResponse)(nil), "messaging.CommitResponse")
	proto.RegisterType((*SubscribeRequest)(nil), "messaging.SubscribeRequest")
	proto.RegisterType((*SubscribeResponse)(nil), "messaging.SubscribeResponse")
	proto.RegisterType((*TrimRequest)(nil), "messaging.TrimRequest")
	proto.RegisterType((*TrimResponse)(nil), "messaging.TrimResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataClient is the client API for Data service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataClient interface {
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error)
	Replicate(ctx context.Context, opts ...grpc.CallOption) (Data_ReplicateClient, error)
	Commit(ctx context.Context, opts ...grpc.CallOption) (Data_CommitClient, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Data_SubscribeClient, error)
	Trim(ctx context.Context, in *TrimRequest, opts ...grpc.CallOption) (*TrimResponse, error)
}

type dataClient struct {
	cc *grpc.ClientConn
}

func NewDataClient(cc *grpc.ClientConn) DataClient {
	return &dataClient{cc}
}

func (c *dataClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error) {
	out := new(AppendResponse)
	err := c.cc.Invoke(ctx, "/messaging.Data/Append", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) Replicate(ctx context.Context, opts ...grpc.CallOption) (Data_ReplicateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Data_serviceDesc.Streams[0], "/messaging.Data/Replicate", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataReplicateClient{stream}
	return x, nil
}

type Data_ReplicateClient interface {
	Send(*ReplicateRequest) error
	CloseAndRecv() (*ReplicateResponse, error)
	grpc.ClientStream
}

type dataReplicateClient struct {
	grpc.ClientStream
}

func (x *dataReplicateClient) Send(m *ReplicateRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataReplicateClient) CloseAndRecv() (*ReplicateResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ReplicateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataClient) Commit(ctx context.Context, opts ...grpc.CallOption) (Data_CommitClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Data_serviceDesc.Streams[1], "/messaging.Data/Commit", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataCommitClient{stream}
	return x, nil
}

type Data_CommitClient interface {
	Send(*CommitRequest) error
	CloseAndRecv() (*CommitResponse, error)
	grpc.ClientStream
}

type dataCommitClient struct {
	grpc.ClientStream
}

func (x *dataCommitClient) Send(m *CommitRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dataCommitClient) CloseAndRecv() (*CommitResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(CommitResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Data_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Data_serviceDesc.Streams[2], "/messaging.Data/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Data_SubscribeClient interface {
	Recv() (*SubscribeResponse, error)
	grpc.ClientStream
}

type dataSubscribeClient struct {
	grpc.ClientStream
}

func (x *dataSubscribeClient) Recv() (*SubscribeResponse, error) {
	m := new(SubscribeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataClient) Trim(ctx context.Context, in *TrimRequest, opts ...grpc.CallOption) (*TrimResponse, error) {
	out := new(TrimResponse)
	err := c.cc.Invoke(ctx, "/messaging.Data/Trim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataServer is the server API for Data service.
type DataServer interface {
	Append(context.Context, *AppendRequest) (*AppendResponse, error)
	Replicate(Data_ReplicateServer) error
	Commit(Data_CommitServer) error
	Subscribe(*SubscribeRequest, Data_SubscribeServer) error
	Trim(context.Context, *TrimRequest) (*TrimResponse, error)
}

func RegisterDataServer(s *grpc.Server, srv DataServer) {
	s.RegisterService(&_Data_serviceDesc, srv)
}

func _Data_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messaging.Data/Append",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_Replicate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataServer).Replicate(&dataReplicateServer{stream})
}

type Data_ReplicateServer interface {
	SendAndClose(*ReplicateResponse) error
	Recv() (*ReplicateRequest, error)
	grpc.ServerStream
}

type dataReplicateServer struct {
	grpc.ServerStream
}

func (x *dataReplicateServer) SendAndClose(m *ReplicateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataReplicateServer) Recv() (*ReplicateRequest, error) {
	m := new(ReplicateRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Data_Commit_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataServer).Commit(&dataCommitServer{stream})
}

type Data_CommitServer interface {
	SendAndClose(*CommitResponse) error
	Recv() (*CommitRequest, error)
	grpc.ServerStream
}

type dataCommitServer struct {
	grpc.ServerStream
}

func (x *dataCommitServer) SendAndClose(m *CommitResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dataCommitServer) Recv() (*CommitRequest, error) {
	m := new(CommitRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Data_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataServer).Subscribe(m, &dataSubscribeServer{stream})
}

type Data_SubscribeServer interface {
	Send(*SubscribeResponse) error
	grpc.ServerStream
}

type dataSubscribeServer struct {
	grpc.ServerStream
}

func (x *dataSubscribeServer) Send(m *SubscribeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Data_Trim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).Trim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messaging.Data/Trim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).Trim(ctx, req.(*TrimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Data_serviceDesc = grpc.ServiceDesc{
	ServiceName: "messaging.Data",
	HandlerType: (*DataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _Data_Append_Handler,
		},
		{
			MethodName: "Trim",
			Handler:    _Data_Trim_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Replicate",
			Handler:       _Data_Replicate_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Commit",
			Handler:       _Data_Commit_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _Data_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "messaging/data.proto",
}

func init() { proto.RegisterFile("messaging/data.proto", fileDescriptor_data_9aa9a57ed7557f0c) }

var fileDescriptor_data_9aa9a57ed7557f0c = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x6d, 0x36, 0xed, 0xc2, 0x0e, 0xec, 0x92, 0x1a, 0xb4, 0x84, 0x80, 0xc4, 0xca, 0xe2, 0x10,
	0x2e, 0x0b, 0x02, 0x84, 0xc4, 0xa1, 0x42, 0x55, 0x2b, 0x2a, 0x8a, 0xc4, 0x21, 0xe5, 0x8e, 0x9c,
	0xc4, 0x8d, 0x22, 0x6d, 0xec, 0xe0, 0x71, 0xf8, 0x0b, 0xfc, 0x4a, 0xfe, 0x4b, 0x95, 0x0f, 0x27,
	0xf6, 0xb6, 0xbd, 0xc5, 0x6f, 0xfc, 0xde, 0x3c, 0xbf, 0x99, 0xc0, 0xb3, 0x8a, 0x23, 0xb2, 0xa2,
	0x14, 0xc5, 0xbb, 0x9c, 0x69, 0xb6, 0xad, 0x95, 0xd4, 0x92, 0x2c, 0x46, 0x94, 0xfe, 0x80, 0xe5,
	0x69, 0x5d, 0x73, 0x91, 0x27, 0xfc, 0x4f, 0xc3, 0x51, 0x93, 0x00, 0xfc, 0xac, 0xcc, 0x43, 0x6f,
	0xe3, 0xc5, 0x47, 0x49, 0xfb, 0xd9, 0x21, 0x28, 0xc2, 0xd9, 0x80, 0xa0, 0x20, 0x6b, 0x98, 0x2b,
	0x9e, 0x49, 0x95, 0x87, 0xfe, 0xc6, 0x8b, 0x17, 0xc9, 0x70, 0xa2, 0x9f, 0x60, 0x65, 0xc4, 0xb0,
	0x96, 0x02, 0xb9, 0xe1, 0x7a, 0x13, 0x37, 0x00, 0xbf, 0x98, 0xd4, 0x0a, 0x14, 0xf4, 0x1b, 0x04,
	0x09, 0xaf, 0x77, 0x65, 0xc6, 0x34, 0x37, 0x2e, 0x22, 0x78, 0x88, 0x5c, 0xfd, 0xe5, 0xea, 0xfb,
	0xf9, 0x40, 0x1e, 0xcf, 0x56, 0xf7, 0x99, 0xd3, 0xfd, 0x29, 0x1c, 0x5b, 0x3a, 0xbd, 0x01, 0xfa,
	0xcf, 0x83, 0xe5, 0x99, 0xac, 0xaa, 0x52, 0x1b, 0xe9, 0xcf, 0xb0, 0x46, 0xcd, 0x94, 0xbe, 0xd8,
	0xc9, 0x94, 0xed, 0xae, 0x5a, 0x54, 0x64, 0xfc, 0x67, 0x53, 0x0d, 0x8d, 0xee, 0xa9, 0x92, 0x10,
	0x1e, 0xc8, 0xeb, 0x6b, 0xe4, 0x1a, 0xc3, 0xd9, 0xc6, 0x8f, 0x8f, 0x12, 0x73, 0x24, 0x6f, 0x60,
	0x99, 0x75, 0x2d, 0x34, 0xcf, 0xcf, 0x1a, 0x8d, 0xa1, 0xdf, 0xd5, 0x5d, 0x90, 0x06, 0xb0, 0x32,
	0x46, 0x06, 0x6f, 0x27, 0x10, 0x5c, 0x35, 0x29, 0x66, 0xaa, 0x4c, 0xc7, 0x87, 0xbf, 0x85, 0x00,
	0x7b, 0xac, 0xd6, 0xa5, 0x14, 0xbf, 0x8b, 0x31, 0xbd, 0x27, 0x36, 0x7e, 0x81, 0x82, 0x9e, 0xc0,
	0xb1, 0x45, 0x9f, 0x02, 0x9f, 0x28, 0xed, 0xe7, 0xbd, 0x71, 0xbd, 0x86, 0x47, 0xbf, 0x54, 0x59,
	0x59, 0x73, 0x77, 0x89, 0x74, 0x05, 0x8f, 0xfb, 0x0b, 0xbd, 0xf4, 0x87, 0xff, 0x33, 0x38, 0x3c,
	0x67, 0x9a, 0x91, 0xaf, 0x30, 0xef, 0xc7, 0x4c, 0xc2, 0xed, 0xb8, 0x49, 0x5b, 0x67, 0x8d, 0xa2,
	0x17, 0x77, 0x54, 0x86, 0x67, 0x1f, 0x90, 0x4b, 0x58, 0x8c, 0x93, 0x22, 0x2f, 0xad, 0x9b, 0xfb,
	0x7b, 0x10, 0xbd, 0xba, 0xbb, 0x68, 0x94, 0x62, 0x8f, 0x9c, 0xc2, 0xbc, 0x8f, 0xd5, 0x31, 0xe3,
	0x8c, 0xdc, 0x31, 0xb3, 0x37, 0x83, 0x56, 0xe2, 0x12, 0x16, 0x63, 0x90, 0x8e, 0x9d, 0xfd, 0xe9,
	0x38, 0x76, 0x6e, 0x65, 0x4f, 0x0f, 0xde, 0x7b, 0xe4, 0x0b, 0x1c, 0xb6, 0xa1, 0x91, 0xb5, 0x75,
	0xd3, 0x8a, 0x39, 0x7a, 0x7e, 0x0b, 0x37, 0xe4, 0x74, 0xde, 0xfd, 0x9c, 0x1f, 0x6f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xce, 0x02, 0x96, 0x76, 0xb4, 0x03, 0x00, 0x00,
}
