apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalog-discovery-deployment
  namespace: scalog
  labels:
    app: scalog-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scalog-discovery
  template:
    metadata:
      labels:
        app: scalog-discovery
    spec:
      serviceAccountName: scalog-service-account
      containers:
      - name: scalog-discovery-node
        image: scalog-discovery
        imagePullPolicy: Never
        ports:
        # Port to server gRPC requests
        - containerPort: 21024
        env:
        - name: NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP