// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Server_RequestType int32

const (
	Server_APPEND    Server_RequestType = 0
	Server_REPLICATE Server_RequestType = 1
	Server_COMMIT    Server_RequestType = 2
	Server_SUBSCRIBE Server_RequestType = 3
	Server_TRIM      Server_RequestType = 4
)

var Server_RequestType_name = map[int32]string{
	0: "APPEND",
	1: "REPLICATE",
	2: "COMMIT",
	3: "SUBSCRIBE",
	4: "TRIM",
}
var Server_RequestType_value = map[string]int32{
	"APPEND":    0,
	"REPLICATE": 1,
	"COMMIT":    2,
	"SUBSCRIBE": 3,
	"TRIM":      4,
}

func (x Server_RequestType) String() string {
	return proto.EnumName(Server_RequestType_name, int32(x))
}
func (Server_RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_data_e1ef3569b341badf, []int{0, 0}
}

type Server struct {
	SenderName              string             `protobuf:"bytes,1,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	SenderReplicaId         int32              `protobuf:"varint,2,opt,name=sender_replica_id,json=senderReplicaId,proto3" json:"sender_replica_id,omitempty"`
	SenderShardId           int32              `protobuf:"varint,3,opt,name=sender_shard_id,json=senderShardId,proto3" json:"sender_shard_id,omitempty"`
	ClientId                int32              `protobuf:"varint,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSeqNum            int32              `protobuf:"varint,5,opt,name=client_seq_num,json=clientSeqNum,proto3" json:"client_seq_num,omitempty"`
	Record                  string             `protobuf:"bytes,6,opt,name=record,proto3" json:"record,omitempty"`
	GlobalSequenceNumber    int32              `protobuf:"varint,7,opt,name=global_sequence_number,json=globalSequenceNumber,proto3" json:"global_sequence_number,omitempty"`
	Cut                     []int32            `protobuf:"varint,8,rep,packed,name=cut,proto3" json:"cut,omitempty"`
	GlobalOrderingThreshold int32              `protobuf:"varint,9,opt,name=global_ordering_threshold,json=globalOrderingThreshold,proto3" json:"global_ordering_threshold,omitempty"`
	RequestType             Server_RequestType `protobuf:"varint,10,opt,name=request_type,json=requestType,proto3,enum=messages.Server_RequestType" json:"request_type,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}           `json:"-"`
	XXX_unrecognized        []byte             `json:"-"`
	XXX_sizecache           int32              `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_e1ef3569b341badf, []int{0}
}
func (m *Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server.Unmarshal(m, b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server.Marshal(b, m, deterministic)
}
func (dst *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(dst, src)
}
func (m *Server) XXX_Size() int {
	return xxx_messageInfo_Server.Size(m)
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *Server) GetSenderReplicaId() int32 {
	if m != nil {
		return m.SenderReplicaId
	}
	return 0
}

func (m *Server) GetSenderShardId() int32 {
	if m != nil {
		return m.SenderShardId
	}
	return 0
}

func (m *Server) GetClientId() int32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *Server) GetClientSeqNum() int32 {
	if m != nil {
		return m.ClientSeqNum
	}
	return 0
}

func (m *Server) GetRecord() string {
	if m != nil {
		return m.Record
	}
	return ""
}

func (m *Server) GetGlobalSequenceNumber() int32 {
	if m != nil {
		return m.GlobalSequenceNumber
	}
	return 0
}

func (m *Server) GetCut() []int32 {
	if m != nil {
		return m.Cut
	}
	return nil
}

func (m *Server) GetGlobalOrderingThreshold() int32 {
	if m != nil {
		return m.GlobalOrderingThreshold
	}
	return 0
}

func (m *Server) GetRequestType() Server_RequestType {
	if m != nil {
		return m.RequestType
	}
	return Server_APPEND
}

func init() {
	proto.RegisterType((*Server)(nil), "messages.Server")
	proto.RegisterEnum("messages.Server_RequestType", Server_RequestType_name, Server_RequestType_value)
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_data_e1ef3569b341badf) }

var fileDescriptor_data_e1ef3569b341badf = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xcf, 0x8b, 0xd4, 0x30,
	0x14, 0xc7, 0xed, 0x76, 0xa6, 0x4e, 0xdf, 0xec, 0xae, 0x35, 0xc8, 0x1a, 0x51, 0xb0, 0x2c, 0x22,
	0xc5, 0x43, 0x0f, 0xea, 0xc9, 0x8b, 0xec, 0x8e, 0x3d, 0x14, 0x6c, 0x77, 0x48, 0xeb, 0xb9, 0x64,
	0x9a, 0xc7, 0x4c, 0xa1, 0xbf, 0x36, 0x69, 0x85, 0xfd, 0x9f, 0xfd, 0x23, 0x24, 0x49, 0x07, 0xbd,
	0xe5, 0x7d, 0x3f, 0x9f, 0x7c, 0x09, 0x2f, 0x00, 0x82, 0x4f, 0x3c, 0x1e, 0xe5, 0x30, 0x0d, 0x64,
	0xd3, 0xa1, 0x52, 0xfc, 0x88, 0xea, 0xf6, 0x8f, 0x0b, 0x5e, 0x81, 0xf2, 0x37, 0x4a, 0xf2, 0x1e,
	0xb6, 0x0a, 0x7b, 0x81, 0xb2, 0xea, 0x79, 0x87, 0xd4, 0x09, 0x9d, 0xc8, 0x67, 0x60, 0xa3, 0x9c,
	0x77, 0x48, 0x3e, 0xc1, 0xcb, 0x45, 0x90, 0x38, 0xb6, 0x4d, 0xcd, 0xab, 0x46, 0xd0, 0x8b, 0xd0,
	0x89, 0xd6, 0xec, 0x85, 0x05, 0xcc, 0xe6, 0xa9, 0x20, 0x1f, 0x61, 0x89, 0x2a, 0x75, 0xe2, 0x52,
	0x68, 0xd3, 0x35, 0xe6, 0x95, 0x8d, 0x0b, 0x9d, 0xa6, 0x82, 0xbc, 0x05, 0xbf, 0x6e, 0x1b, 0xec,
	0x27, 0x6d, 0xac, 0x8c, 0xb1, 0xb1, 0x41, 0x2a, 0xc8, 0x07, 0xb8, 0x5e, 0xa0, 0xc2, 0xc7, 0xaa,
	0x9f, 0x3b, 0xba, 0x36, 0xc6, 0xa5, 0x4d, 0x0b, 0x7c, 0xcc, 0xe7, 0x8e, 0xdc, 0x80, 0x27, 0xb1,
	0x1e, 0xa4, 0xa0, 0x9e, 0x79, 0xf2, 0x32, 0x91, 0xaf, 0x70, 0x73, 0x6c, 0x87, 0x03, 0x6f, 0xf5,
	0xed, 0x19, 0xfb, 0x1a, 0x75, 0xc5, 0x01, 0x25, 0x7d, 0x6e, 0x5a, 0x5e, 0x59, 0x5a, 0x2c, 0x30,
	0x37, 0x8c, 0x04, 0xe0, 0xd6, 0xf3, 0x44, 0x37, 0xa1, 0x1b, 0xad, 0x99, 0x3e, 0x92, 0x6f, 0xf0,
	0x66, 0xe9, 0x19, 0xa4, 0x40, 0xd9, 0xf4, 0xc7, 0x6a, 0x3a, 0x49, 0x54, 0xa7, 0xa1, 0x15, 0xd4,
	0x37, 0x55, 0xaf, 0xad, 0xf0, 0xb0, 0xf0, 0xf2, 0x8c, 0xc9, 0x77, 0xb8, 0x94, 0xba, 0x5f, 0x4d,
	0xd5, 0xf4, 0x34, 0x22, 0x85, 0xd0, 0x89, 0xae, 0x3f, 0xbf, 0x8b, 0xcf, 0xfb, 0x8f, 0xed, 0xee,
	0x63, 0x66, 0xa5, 0xf2, 0x69, 0x44, 0xb6, 0x95, 0xff, 0x86, 0xdb, 0x0c, 0xb6, 0xff, 0x31, 0x02,
	0xe0, 0xdd, 0xed, 0xf7, 0x49, 0xfe, 0x23, 0x78, 0x46, 0xae, 0xc0, 0x67, 0xc9, 0xfe, 0x67, 0xba,
	0xbb, 0x2b, 0x93, 0xc0, 0xd1, 0x68, 0xf7, 0x90, 0x65, 0x69, 0x19, 0x5c, 0x68, 0x54, 0xfc, 0xba,
	0x2f, 0x76, 0x2c, 0xbd, 0x4f, 0x02, 0x97, 0x6c, 0x60, 0x55, 0xb2, 0x34, 0x0b, 0x56, 0x07, 0xcf,
	0xfc, 0xff, 0x97, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x70, 0x8f, 0xdf, 0x0d, 0x02, 0x00,
	0x00,
}
