// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Order_RequestType int32

const (
	Order_REPORT   Order_RequestType = 0
	Order_REGISTER Order_RequestType = 1
	Order_FINALIZE Order_RequestType = 2
)

var Order_RequestType_name = map[int32]string{
	0: "REPORT",
	1: "REGISTER",
	2: "FINALIZE",
}
var Order_RequestType_value = map[string]int32{
	"REPORT":   0,
	"REGISTER": 1,
	"FINALIZE": 2,
}

func (x Order_RequestType) String() string {
	return proto.EnumName(Order_RequestType_name, int32(x))
}
func (Order_RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_order_3de257e7e3ab9708, []int{0, 0}
}

type Order struct {
	ReplicaName          string   `protobuf:"bytes,1,opt,name=replica_name,json=replicaName,proto3" json:"replica_name,omitempty"`
	ShardId              int32    `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	ReplicaId            int32    `protobuf:"varint,3,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	TentativeCut         []int32  `protobuf:"varint,4,rep,packed,name=tentative_cut,json=tentativeCut,proto3" json:"tentative_cut,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_order_3de257e7e3ab9708, []int{0}
}
func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (dst *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(dst, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetReplicaName() string {
	if m != nil {
		return m.ReplicaName
	}
	return ""
}

func (m *Order) GetShardId() int32 {
	if m != nil {
		return m.ShardId
	}
	return 0
}

func (m *Order) GetReplicaId() int32 {
	if m != nil {
		return m.ReplicaId
	}
	return 0
}

func (m *Order) GetTentativeCut() []int32 {
	if m != nil {
		return m.TentativeCut
	}
	return nil
}

func init() {
	proto.RegisterType((*Order)(nil), "messages.Order")
	proto.RegisterEnum("messages.Order_RequestType", Order_RequestType_name, Order_RequestType_value)
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_order_3de257e7e3ab9708) }

var fileDescriptor_order_3de257e7e3ab9708 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x46, 0xcd, 0x8c, 0x1d, 0x3b, 0xb7, 0x15, 0x4a, 0x56, 0x71, 0x21, 0xd4, 0x71, 0xd3, 0x95,
	0x1b, 0xf1, 0x01, 0x44, 0xa2, 0x04, 0xa4, 0x95, 0x6b, 0x57, 0x6e, 0x4a, 0x6c, 0x2e, 0x1a, 0xb0,
	0x3f, 0x26, 0xa9, 0xe0, 0xdb, 0xf9, 0x68, 0xd2, 0x52, 0x5d, 0x9e, 0x73, 0xf8, 0x16, 0x1f, 0x24,
	0x83, 0x33, 0xe4, 0xae, 0x46, 0x37, 0x84, 0x81, 0xc7, 0x1d, 0x79, 0xaf, 0xdf, 0xc8, 0x1f, 0x7e,
	0x18, 0x44, 0xd5, 0x5c, 0xf8, 0x05, 0xa4, 0x8e, 0xc6, 0x0f, 0xdb, 0xea, 0xa6, 0xd7, 0x1d, 0x09,
	0x96, 0xb3, 0x62, 0x8f, 0xc9, 0xea, 0x4a, 0xdd, 0x11, 0x3f, 0x83, 0xd8, 0xbf, 0x6b, 0x67, 0x1a,
	0x6b, 0xc4, 0x26, 0x67, 0x45, 0x84, 0x27, 0x0b, 0x2b, 0xc3, 0xcf, 0x01, 0xfe, 0xd6, 0xd6, 0x88,
	0xed, 0x12, 0xf7, 0xab, 0x51, 0x86, 0x5f, 0xc2, 0x69, 0xa0, 0x3e, 0xe8, 0x60, 0xbf, 0xa8, 0x69,
	0xa7, 0x20, 0x8e, 0xf3, 0x6d, 0x11, 0x61, 0xfa, 0x2f, 0xef, 0xa6, 0x70, 0xb8, 0x81, 0x04, 0xe9,
	0x73, 0x22, 0x1f, 0xea, 0xef, 0x91, 0x38, 0xc0, 0x0e, 0xe5, 0x53, 0x85, 0x75, 0x76, 0xc4, 0x53,
	0x88, 0x51, 0x3e, 0xa8, 0xe7, 0x5a, 0x62, 0xc6, 0x66, 0xba, 0x57, 0xe5, 0xed, 0xa3, 0x7a, 0x91,
	0xd9, 0xe6, 0x75, 0xb7, 0x7c, 0xba, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xc3, 0xe1, 0xde, 0x92,
	0xe2, 0x00, 0x00, 0x00,
}
