// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messaging/order.proto

package messaging

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Cut struct {
	// Array of len numReplicas
	Cut                  []int32  `protobuf:"varint,1,rep,packed,name=cut,proto3" json:"cut,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cut) Reset()         { *m = Cut{} }
func (m *Cut) String() string { return proto.CompactTextString(m) }
func (*Cut) ProtoMessage()    {}
func (*Cut) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8af3e412e3326d2, []int{0}
}

func (m *Cut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cut.Unmarshal(m, b)
}
func (m *Cut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cut.Marshal(b, m, deterministic)
}
func (m *Cut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cut.Merge(m, src)
}
func (m *Cut) XXX_Size() int {
	return xxx_messageInfo_Cut.Size(m)
}
func (m *Cut) XXX_DiscardUnknown() {
	xxx_messageInfo_Cut.DiscardUnknown(m)
}

var xxx_messageInfo_Cut proto.InternalMessageInfo

func (m *Cut) GetCut() []int32 {
	if m != nil {
		return m.Cut
	}
	return nil
}

type ShardView struct {
	// Key: ReplicaID, Value: replica cuts
	Replicas             map[int32]*Cut `protobuf:"bytes,1,rep,name=replicas,proto3" json:"replicas,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ShardView) Reset()         { *m = ShardView{} }
func (m *ShardView) String() string { return proto.CompactTextString(m) }
func (*ShardView) ProtoMessage()    {}
func (*ShardView) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8af3e412e3326d2, []int{1}
}

func (m *ShardView) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShardView.Unmarshal(m, b)
}
func (m *ShardView) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShardView.Marshal(b, m, deterministic)
}
func (m *ShardView) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardView.Merge(m, src)
}
func (m *ShardView) XXX_Size() int {
	return xxx_messageInfo_ShardView.Size(m)
}
func (m *ShardView) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardView.DiscardUnknown(m)
}

var xxx_messageInfo_ShardView proto.InternalMessageInfo

func (m *ShardView) GetReplicas() map[int32]*Cut {
	if m != nil {
		return m.Replicas
	}
	return nil
}

type ReportRequest struct {
	// Key: ShardID, Value: Shard cuts
	Shards map[int32]*ShardView `protobuf:"bytes,1,rep,name=shards,proto3" json:"shards,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Non-nil only if the ordering layer wishes to propose a finalization these particular shards after k cuts
	Finalize map[int32]int32 `protobuf:"bytes,2,rep,name=finalize,proto3" json:"finalize,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	// True if this is a request to batch and send the committedcuts
	Batch                bool     `protobuf:"varint,3,opt,name=batch,proto3" json:"batch,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportRequest) Reset()         { *m = ReportRequest{} }
func (m *ReportRequest) String() string { return proto.CompactTextString(m) }
func (*ReportRequest) ProtoMessage()    {}
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8af3e412e3326d2, []int{2}
}

func (m *ReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRequest.Unmarshal(m, b)
}
func (m *ReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRequest.Marshal(b, m, deterministic)
}
func (m *ReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRequest.Merge(m, src)
}
func (m *ReportRequest) XXX_Size() int {
	return xxx_messageInfo_ReportRequest.Size(m)
}
func (m *ReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRequest proto.InternalMessageInfo

func (m *ReportRequest) GetShards() map[int32]*ShardView {
	if m != nil {
		return m.Shards
	}
	return nil
}

func (m *ReportRequest) GetFinalize() map[int32]int32 {
	if m != nil {
		return m.Finalize
	}
	return nil
}

func (m *ReportRequest) GetBatch() bool {
	if m != nil {
		return m.Batch
	}
	return false
}

type ReportResponse struct {
	// Key: ShardID, Value: Commited cuts
	CommitedCuts map[int32]*Cut `protobuf:"bytes,1,rep,name=commitedCuts,proto3" json:"commitedCuts,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// GSN to start computing at
	StartGSN int32 `protobuf:"varint,2,opt,name=startGSN,proto3" json:"startGSN,omitempty"`
	// Array of shards that have been finalized in this batch
	Finalize             []int32  `protobuf:"varint,3,rep,packed,name=finalize,proto3" json:"finalize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportResponse) Reset()         { *m = ReportResponse{} }
func (m *ReportResponse) String() string { return proto.CompactTextString(m) }
func (*ReportResponse) ProtoMessage()    {}
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8af3e412e3326d2, []int{3}
}

func (m *ReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportResponse.Unmarshal(m, b)
}
func (m *ReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportResponse.Marshal(b, m, deterministic)
}
func (m *ReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportResponse.Merge(m, src)
}
func (m *ReportResponse) XXX_Size() int {
	return xxx_messageInfo_ReportResponse.Size(m)
}
func (m *ReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReportResponse proto.InternalMessageInfo

func (m *ReportResponse) GetCommitedCuts() map[int32]*Cut {
	if m != nil {
		return m.CommitedCuts
	}
	return nil
}

func (m *ReportResponse) GetStartGSN() int32 {
	if m != nil {
		return m.StartGSN
	}
	return 0
}

func (m *ReportResponse) GetFinalize() []int32 {
	if m != nil {
		return m.Finalize
	}
	return nil
}

type FinalizeRequest struct {
	// Array of shards to finalize after k cuts
	Shards               map[int32]int32 `protobuf:"bytes,1,rep,name=shards,proto3" json:"shards,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *FinalizeRequest) Reset()         { *m = FinalizeRequest{} }
func (m *FinalizeRequest) String() string { return proto.CompactTextString(m) }
func (*FinalizeRequest) ProtoMessage()    {}
func (*FinalizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8af3e412e3326d2, []int{4}
}

func (m *FinalizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinalizeRequest.Unmarshal(m, b)
}
func (m *FinalizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinalizeRequest.Marshal(b, m, deterministic)
}
func (m *FinalizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinalizeRequest.Merge(m, src)
}
func (m *FinalizeRequest) XXX_Size() int {
	return xxx_messageInfo_FinalizeRequest.Size(m)
}
func (m *FinalizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FinalizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FinalizeRequest proto.InternalMessageInfo

func (m *FinalizeRequest) GetShards() map[int32]int32 {
	if m != nil {
		return m.Shards
	}
	return nil
}

type FinalizeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinalizeResponse) Reset()         { *m = FinalizeResponse{} }
func (m *FinalizeResponse) String() string { return proto.CompactTextString(m) }
func (*FinalizeResponse) ProtoMessage()    {}
func (*FinalizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8af3e412e3326d2, []int{5}
}

func (m *FinalizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinalizeResponse.Unmarshal(m, b)
}
func (m *FinalizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinalizeResponse.Marshal(b, m, deterministic)
}
func (m *FinalizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinalizeResponse.Merge(m, src)
}
func (m *FinalizeResponse) XXX_Size() int {
	return xxx_messageInfo_FinalizeResponse.Size(m)
}
func (m *FinalizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FinalizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FinalizeResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Cut)(nil), "messaging.Cut")
	proto.RegisterType((*ShardView)(nil), "messaging.ShardView")
	proto.RegisterMapType((map[int32]*Cut)(nil), "messaging.ShardView.ReplicasEntry")
	proto.RegisterType((*ReportRequest)(nil), "messaging.ReportRequest")
	proto.RegisterMapType((map[int32]int32)(nil), "messaging.ReportRequest.FinalizeEntry")
	proto.RegisterMapType((map[int32]*ShardView)(nil), "messaging.ReportRequest.ShardsEntry")
	proto.RegisterType((*ReportResponse)(nil), "messaging.ReportResponse")
	proto.RegisterMapType((map[int32]*Cut)(nil), "messaging.ReportResponse.CommitedCutsEntry")
	proto.RegisterType((*FinalizeRequest)(nil), "messaging.FinalizeRequest")
	proto.RegisterMapType((map[int32]int32)(nil), "messaging.FinalizeRequest.ShardsEntry")
	proto.RegisterType((*FinalizeResponse)(nil), "messaging.FinalizeResponse")
}

func init() { proto.RegisterFile("messaging/order.proto", fileDescriptor_f8af3e412e3326d2) }

var fileDescriptor_f8af3e412e3326d2 = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xdd, 0x6e, 0x94, 0x40,
	0x14, 0x76, 0x96, 0xb0, 0xd2, 0xb3, 0xb6, 0xd6, 0xc9, 0x1a, 0x71, 0xbc, 0x21, 0xa4, 0x31, 0x44,
	0x13, 0x34, 0xeb, 0x8d, 0x7f, 0xe9, 0x45, 0x49, 0xeb, 0x85, 0x89, 0x24, 0x34, 0xf1, 0x7e, 0x0a,
	0x63, 0x4b, 0xba, 0x0b, 0xeb, 0xcc, 0xe0, 0x66, 0x7d, 0x06, 0x1f, 0xc0, 0x17, 0xf1, 0x59, 0x7c,
	0x07, 0x9f, 0xc2, 0x0c, 0x30, 0x38, 0xac, 0x10, 0x13, 0x7b, 0xc7, 0x70, 0xbe, 0xef, 0x3b, 0xdf,
	0xf9, 0xe6, 0x00, 0xdc, 0x5f, 0x31, 0x21, 0xe8, 0x65, 0x5e, 0x5c, 0x3e, 0x2b, 0x79, 0xc6, 0x78,
	0xb8, 0xe6, 0xa5, 0x2c, 0xf1, 0x5e, 0xf7, 0xda, 0x7f, 0x00, 0x56, 0x54, 0x49, 0x7c, 0x08, 0x56,
	0x5a, 0x49, 0x17, 0x79, 0x56, 0x60, 0x27, 0xea, 0xd1, 0xff, 0x8e, 0x60, 0xef, 0xfc, 0x8a, 0xf2,
	0xec, 0x63, 0xce, 0x36, 0xf8, 0x18, 0x1c, 0xce, 0xd6, 0xcb, 0x3c, 0xa5, 0xa2, 0x06, 0xcd, 0x16,
	0x7e, 0xd8, 0x89, 0x84, 0x1d, 0x2e, 0x4c, 0x5a, 0xd0, 0x69, 0x21, 0xf9, 0x36, 0xe9, 0x38, 0xe4,
	0x3d, 0xec, 0xf7, 0x4a, 0xaa, 0xe1, 0x35, 0xdb, 0xba, 0xc8, 0x43, 0xaa, 0xe1, 0x35, 0xdb, 0xe2,
	0x23, 0xb0, 0xbf, 0xd0, 0x65, 0xc5, 0xdc, 0x89, 0x87, 0x82, 0xd9, 0xe2, 0xc0, 0xd0, 0x8f, 0x2a,
	0x99, 0x34, 0xc5, 0xd7, 0x93, 0x97, 0xc8, 0xff, 0x31, 0xa9, 0xd5, 0x4a, 0x2e, 0x13, 0xf6, 0xb9,
	0x62, 0x42, 0xe2, 0xb7, 0x30, 0x15, 0xca, 0x83, 0x36, 0x77, 0x64, 0x90, 0x7b, 0xc8, 0xc6, 0x6a,
	0x6b, 0xaf, 0xe5, 0xe0, 0x13, 0x70, 0x3e, 0xe5, 0x05, 0x5d, 0xe6, 0x5f, 0x55, 0x73, 0xc5, 0x7f,
	0x3c, 0xca, 0x3f, 0x6b, 0x81, 0xed, 0x80, 0x9a, 0x87, 0xe7, 0x60, 0x5f, 0x50, 0x99, 0x5e, 0xb9,
	0x96, 0x87, 0x02, 0x27, 0x69, 0x0e, 0x24, 0x86, 0x99, 0xd1, 0x70, 0x60, 0xe8, 0x27, 0xfd, 0xa1,
	0xe7, 0x43, 0xa1, 0x1a, 0xa3, 0x93, 0x37, 0xb0, 0xdf, 0x73, 0x30, 0x20, 0x39, 0x37, 0x25, 0x6d,
	0x33, 0xb7, 0x5f, 0x08, 0x0e, 0xf4, 0x34, 0x62, 0x5d, 0x16, 0x82, 0xe1, 0x18, 0xee, 0xa4, 0xe5,
	0x6a, 0x95, 0x4b, 0x96, 0x45, 0x95, 0xd4, 0xf1, 0x3d, 0x1d, 0x18, 0xbf, 0x21, 0x84, 0x91, 0x81,
	0x6e, 0x32, 0xe8, 0x09, 0x60, 0x02, 0x8e, 0x90, 0x94, 0xcb, 0x77, 0xe7, 0x1f, 0x5a, 0x03, 0xdd,
	0x59, 0xd5, 0xba, 0x9c, 0xad, 0x7a, 0xd3, 0xba, 0x33, 0x89, 0xe1, 0xde, 0x5f, 0xd2, 0x37, 0x5a,
	0x92, 0x6f, 0x08, 0xee, 0xea, 0xa8, 0xf4, 0x9a, 0x1c, 0xef, 0xac, 0x89, 0x79, 0xcd, 0x3b, 0xd8,
	0xa1, 0x45, 0x21, 0xaf, 0xfe, 0x75, 0x9d, 0xe3, 0xd9, 0x63, 0x38, 0xfc, 0xd3, 0xa1, 0xc9, 0x72,
	0xf1, 0x13, 0x81, 0x1d, 0xab, 0xcf, 0x12, 0x47, 0x30, 0x6d, 0x72, 0xc6, 0xee, 0xd8, 0xe6, 0x91,
	0x87, 0xa3, 0x97, 0xe2, 0xdf, 0x0a, 0xd0, 0x73, 0x84, 0x4f, 0xe0, 0xf6, 0x59, 0xc9, 0x37, 0x94,
	0x67, 0xff, 0xad, 0x82, 0x4f, 0xc1, 0xd1, 0x36, 0x31, 0x19, 0x4f, 0x87, 0x3c, 0x1a, 0xac, 0x69,
	0xa1, 0x8b, 0x69, 0xfd, 0x9f, 0x79, 0xf1, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x07, 0xec, 0xaa, 0xd7,
	0x80, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderClient interface {
	Report(ctx context.Context, opts ...grpc.CallOption) (Order_ReportClient, error)
	Forward(ctx context.Context, opts ...grpc.CallOption) (Order_ForwardClient, error)
	Finalize(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (*FinalizeResponse, error)
}

type orderClient struct {
	cc *grpc.ClientConn
}

func NewOrderClient(cc *grpc.ClientConn) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) Report(ctx context.Context, opts ...grpc.CallOption) (Order_ReportClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Order_serviceDesc.Streams[0], "/messaging.Order/Report", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderReportClient{stream}
	return x, nil
}

type Order_ReportClient interface {
	Send(*ReportRequest) error
	Recv() (*ReportResponse, error)
	grpc.ClientStream
}

type orderReportClient struct {
	grpc.ClientStream
}

func (x *orderReportClient) Send(m *ReportRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *orderReportClient) Recv() (*ReportResponse, error) {
	m := new(ReportResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *orderClient) Forward(ctx context.Context, opts ...grpc.CallOption) (Order_ForwardClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Order_serviceDesc.Streams[1], "/messaging.Order/Forward", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderForwardClient{stream}
	return x, nil
}

type Order_ForwardClient interface {
	Send(*ReportRequest) error
	CloseAndRecv() (*ReportResponse, error)
	grpc.ClientStream
}

type orderForwardClient struct {
	grpc.ClientStream
}

func (x *orderForwardClient) Send(m *ReportRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *orderForwardClient) CloseAndRecv() (*ReportResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ReportResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *orderClient) Finalize(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (*FinalizeResponse, error) {
	out := new(FinalizeResponse)
	err := c.cc.Invoke(ctx, "/messaging.Order/Finalize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
type OrderServer interface {
	Report(Order_ReportServer) error
	Forward(Order_ForwardServer) error
	Finalize(context.Context, *FinalizeRequest) (*FinalizeResponse, error)
}

func RegisterOrderServer(s *grpc.Server, srv OrderServer) {
	s.RegisterService(&_Order_serviceDesc, srv)
}

func _Order_Report_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrderServer).Report(&orderReportServer{stream})
}

type Order_ReportServer interface {
	Send(*ReportResponse) error
	Recv() (*ReportRequest, error)
	grpc.ServerStream
}

type orderReportServer struct {
	grpc.ServerStream
}

func (x *orderReportServer) Send(m *ReportResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *orderReportServer) Recv() (*ReportRequest, error) {
	m := new(ReportRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Order_Forward_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrderServer).Forward(&orderForwardServer{stream})
}

type Order_ForwardServer interface {
	SendAndClose(*ReportResponse) error
	Recv() (*ReportRequest, error)
	grpc.ServerStream
}

type orderForwardServer struct {
	grpc.ServerStream
}

func (x *orderForwardServer) SendAndClose(m *ReportResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *orderForwardServer) Recv() (*ReportRequest, error) {
	m := new(ReportRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Order_Finalize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).Finalize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/messaging.Order/Finalize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).Finalize(ctx, req.(*FinalizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Order_serviceDesc = grpc.ServiceDesc{
	ServiceName: "messaging.Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Finalize",
			Handler:    _Order_Finalize_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Report",
			Handler:       _Order_Report_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Forward",
			Handler:       _Order_Forward_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "messaging/order.proto",
}
